#!/bin/bash
gcc -O0 -Wall -Werror test.c -o test
# NAME=$(cat /proc/cpuinfo | grep -E 'model name' | head -1 )
for sz in 10 100 1000 10000 100000 1000000 10000000 100000000
do
    for factor in 1 2 3 4 5 6 7 8 9 10
    do
        inputsz=$(($sz*$factor))
        ./test $inputsz >> res.txt
    done
done
mkdir -p data
mv *.txt data/
echo "Please email the contents of the data folder, as well as the name/type/model of your processor (if known), to agoldfa7@u.rochester.edu"
echo "Thank you!"
